### PR TITLE
Cleanup deps, remove unused browser service

### PR DESCRIPTION
**Pull request by andrewvc**
This is to stop `npm audit` from complaining. Updates some libs, removes unused browser service experiment (run the browser in a separate process without requiring it to be a subprocess), and also removes the unused `npm-pack-all` library.

Takes over from https://github.com/elastic/synthetics/pull/421

### CODE REVIEW

**Review by vigneshshanmugam — CHANGES_REQUESTED** [review]
Removing browser service is going to be a good chunk of work. 

+ Have to stop tests running in the browser service - https://github.com/elastic/synthetics/blob/0114b0f361688a7cda978b2485b08b8b6d5e769e/package.json#L17

+ Gets rid of browser service tests and global setup - https://github.com/elastic/synthetics/blob/main/__tests__/utils/jest-global-setup.ts
+ Also replace all occurances of `WSENDPOINT` and refactor all tests.

**Comment by andrewvc** [comment]
I've brought that back now, sorry :)

**Comment by andrewvc** [comment]
I've also removed the unused `pkg` task left over from the very early days

**Review by vigneshshanmugam — APPROVED** [review]
Lgtm

**Pull request merged**
