### PR TITLE
feat: support every 10 and 30 seconds intervals for lightweight monitors

### PR DESCRIPTION
**Pull request by shahzad31**
fixes https://github.com/elastic/synthetics/issues/930
support 10 and s30 seconds intervals for lightweight monitors !!

Some changes were also needed in kibana https://github.com/elastic/kibana/pull/185920

### CODE REVIEW

**Review by vigneshshanmugam — COMMENTED** [review]
Thanks @shahzad31 Code looks good. Few thoughts. 

- What happens if users push these changes to an older version of Kibana? Does the API reject the monitors? 
- Can we add a follow up doc issue and add the relevant info for Lightweight and Browser monitor and also suggest from what stack we start supporting these new schedules.

**Comment by shahzad31** [comment]
> Thanks @shahzad31 Code looks good. Few thoughts.
> 
> * What happens if users push these changes to an older version of Kibana? Does the API reject the monitors?
> * Can we add a follow up doc issue and add the relevant info for Lightweight and Browser monitor and also suggest from what stack we start supporting these new schedules.

Usage against old kibana will throw an error, since we do validation there.

**Review by vigneshshanmugam — APPROVED** [review]

**Comment by MakoWish** [comment]
What version was this supposed to work on? We are on 8.14.1, and 1 minute is still the quickest interval we can choose.

**Comment by shahzad31** [comment]
@MakoWish it will be shipped in 8.15.0, which is just around the corner.

**Pull request merged**
